data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data1 <- subset(data, Date == "1/2/2007" | Date == "2/2/2007")
y <- paste(data1$Date, data1$Time)
z <- strptime(y, "%d/%m/%Y %H:%M:%S")
png(file = "plot2.png")
plot(z, data1$Global_active_power, xlab = "", ylab = "Global Active Power (kilowatts)", type = "n")
lines(z, data1$Global_active_power)
dev.off()
rm(list = ls())