data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data1 <- subset(data, Date == "1/2/2007" | Date == "2/2/2007")
y <- paste(data1$Date, data1$Time)
z <- strptime(y, "%d/%m/%Y %H:%M:%S")
png(file = "plot4.png")
par(mfcol = c(2, 2), mar = c(4, 4, 2, 1))
plot(z, data1$Global_active_power, xlab = "", ylab = "Global Active Power", type = "n")
lines(z, data1$Global_active_power)
plot(z, data1$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
lines(z, data1$Sub_metering_1)
lines(z, data1$Sub_metering_2, col = "red")
lines(z, data1$Sub_metering_3, col = "blue")
legend("topright", lty = 1, cex = 0.75, , bty = "n", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(z, data1$Voltage, xlab = "datetime", ylab = "Voltage", type = "n")
lines(z, data1$Voltage)
plot(z, data1$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "n")
lines(z, data1$Global_reactive_power)
dev.off()
rm(list = ls())