data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data1 <- subset(data, Date == "1/2/2007" | Date == "2/2/2007")
y <- paste(data1$Date, data1$Time)
z <- strptime(y, "%d/%m/%Y %H:%M:%S")
png(file = "plot3.png")
plot(z, data1$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
lines(z, data1$Sub_metering_1)
lines(z, data1$Sub_metering_2, col = "red")
lines(z, data1$Sub_metering_3, col = "blue")
legend("topright", lty = 1, cex = 0.75, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
rm(list = ls())