data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data1 <- subset(data, Date == "1/2/2007" | Date == "2/2/2007")
png(file = "plot1.png")
hist(data1$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()
rm(list = ls())